### ISSUE TITLE
PA Review: Tracks

### ISSUE THREAD

**Issue by baustgen** [baustgen/Lyrical#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by baustgen** [comment]
I've updated Heroku with all of the changes I made this morning; am I good to move on to Annotations?

**Comment by ryan-mapa** [comment]
Go for it!

**Comment by ryan-mapa** [comment]
Looking good!
